### ISSUE TITLE
FFmpegVideoWriter::writeNextVideoFrame (const juce::Image& image, const AVRational timestamp) coming soon?

### ISSUE THREAD

**Issue by matkatmusic** [filmstro/filmstro_ffmpeg#3]
Howdy.   Just curious if this will ever be implemented.  it would be EXTREMELY handy!

https://github.com/filmstro/filmstro_ffmpeg/blob/master/modules/filmstro_ffmpeg/filmstro_ffmpeg_FFmpegVideoWriter.cpp#L324

`
void FFmpegVideoWriter::writeNextVideoFrame (const juce::Image& image, const AVRational timestamp) {
// TODO: use scaler and add interface for image processing / e.g. branding
}
`

Thank you so much for creating this API!   ffmpeg is not easy to use!

**Comment by ffAudio** [comment]
I'm on it... not full time but continuously...
Any help or contribution is also very welcome :-)

**Comment by ffAudio** [comment]
There is an initial version up now, see the AnimationWriter example... but it needs fixing, the video is black...

**Comment by matkatmusic** [comment]
I was looking at this code for sws_scale(): 

https://github.com/FFmpeg/FFmpeg/blob/03ce71e4a1187340720e1569ac96c285c145a1f7/libswscale/swscale.c#L753

is `uint8_t* source[4] = {data.data, data.data, data.data, data.data};` the correct way to populate `const uint8_t * const srcSlice[]`? 
srcSlice is only really used on https://github.com/FFmpeg/FFmpeg/blob/03ce71e4a1187340720e1569ac96c285c145a1f7/libswscale/swscale.c#L824 
I do see that they copy srcSlice into `const uint8_t *src2[4]`; on line 824, but there's nothing that suggests they want 4 of 'em, other than at line 852 where they cast element [1] of srcSlice into a uint32_t (what happens to element [0]? ), but that's only if the format is PAL. 

i'm referring to https://github.com/filmstro/filmstro_ffmpeg/blob/master/modules/filmstro_ffmpeg/filmstro_ffmpeg_FFmpegVideoScaler.cpp#L104 where you read from your Juce::image and write it to an AVFrame using sws_scale().  Maybe that's why you're getting only black images written to the video?  

Also, on this line: https://github.com/filmstro/filmstro_ffmpeg/blob/master/modules/filmstro_ffmpeg/filmstro_ffmpeg_FFmpegVideoWriter.cpp#L380 you set the pixel format as AV_PIX_FMT_BGR0
your canvas that you're writing to in the update() loop in the example is RGB https://github.com/filmstro/filmstro_ffmpeg/blob/master/examples/AnimationWriter/Source/MainComponent.cpp#L36 Perhaps that's part of the problem? 

maybe you meant https://ffmpeg.org/doxygen/trunk/pixfmt_8h.html#a9a8e335cf3be472042bc9f0cf80cd4c5ab9fcc01ba1689d75e4bc2080a347e1d0 ? AV_PIX_FMT_RGB0

**Comment by ffAudio** [comment]
Thanks matkatmusic for helping debugging.

> is uint8_t* source[4] = {data.data, data.data, data.data, data.data}; the correct way to populate const uint8_t * const srcSlice[]?

Yes, because the source data, i.e. the juce::Image uses interleaved pixel data instead of colour planes, in which case the scaler only uses the first pointer, but for consistency the unused pointers may point to the same data.
That's different for AV_PIX_FMT_YUV420P, the P stands for planar, meaning that each color plane is separate; data[0] = YYYY, data[1] = UUUU, data[2] = VVVV, data[3] is unused, because no alpha is involved. Look here: https://en.wikipedia.org/wiki/YUV#Y.E2.80.B2UV420p_.28and_Y.E2.80.B2V12_or_YV12.29_to_RGB888_conversion

> maybe you meant https://ffmpeg.org/doxygen/trunk/pixfmt_8h.html#a9a8e335cf3be472042bc9f0cf80cd4c5ab9fcc01ba1689d75e4bc2080a347e1d0 ? AV_PIX_FMT_RGB0

The method above does the opposite thing, and that one works. I also expected RGB0, but it turned out to be the opposite. But maybe it's worth checking.
However, out of desperation I also tried to write random noise into the pixel data of AVFrame. The file size increased, which makes sense, but it remained black, so I think the problem is in setting up the format correctly... but I may be wrong...

**Comment by matkatmusic** [comment]
I had a bit of discussion about that spot with Mavrik in #ffmpeg, you might check the channel log and see what he suggested.

**Comment by ffAudio** [comment]
Sorry, can't find it... mind sending a link and time?

**Comment by matkatmusic** [comment]
it just happened.  so it's not on the archive yet.  

> thanks
matkatmusic
anyone have any experience writing raw RGB uint8_t's into an AVFrame?  
matkatmusic
I'm helping another coder figure out why this call to sws_scale() isn't writing data correctly (the output video is all black)
matkatmusic
https://github.com/filmstro/filmstro_ffmpeg/blob/master/modules/filmstro_ffmpeg/filmstro_ffmpeg_FFmpegVideoScaler.cpp#L104
Mavrik
why are you setting data 4 times? O.o
matkatmusic
See this reply: https://github.com/filmstro/filmstro_ffmpeg/issues/3#issuecomment-287697897
matkatmusic
I asked the same thing
Mavrik
That's fugly.
matkatmusic
I didn't write that github lib.  i'm just helping him get it working.
Mavrik
but probably not critically wrong
matkatmusic
the ffmpeg library is really hard to use
Mavrik
hard to say what's actually going on in that piece of code
Mavrik
because the code architecture is horrible
matkatmusic
if you're trying to use it via the API, i mean.  
Mavrik
it accepts pixel format as a parameter?
Mavrik
and then it just ignores that and magically infers it needs 4 bytes per pixel in a single plane?
Mavrik
wat.
matkatmusic
what are you referring to?
matkatmusic
I'm assuming you're referring to this: https://github.com/FFmpeg/FFmpeg/blob/03ce71e4a1187340720e1569ac96c285c145a1f7/libswscale/swscale.c#L824
matkatmusic
er, more specifically https://github.com/FFmpeg/FFmpeg/blob/03ce71e4a1187340720e1569ac96c285c145a1f7/libswscale/swscale.c#L753
matkatmusic
that's the start of the function
matkatmusic
sws_scale()
Mavrik
I'm refering to this: https://github.com/filmstro/filmstro_ffmpeg/blob/master/modules/filmstro_ffmpeg/filmstro_ffmpeg_FFmpegVideoScaler.cpp#L82
Mavrik
vs this: https://github.com/filmstro/filmstro_ffmpeg/blob/master/modules/filmstro_ffmpeg/filmstro_ffmpeg_FFmpegVideoScaler.cpp#L58
Mavrik
the "scaler" gets input format as a parameter
Mavrik
but then it hardcodes the size of the plane
Mavrik
I suggest you take a look for those kind of code smells:
Mavrik
1.) Is the format set properly for your encoder?
matkatmusic
I wish mcjack were here to cmoment, cuz that's his code.
matkatmusic
comment
Mavrik
2.) Is the AVFrame actually allocated (your pointers should be valid)
Mavrik
3.) Do you set a proper RGB vs. output format?
Mavrik
4.) Do you get an error/warning in the log when running he scaler
Mavrik
All of that can easily be checked with a debugger through that code

**Comment by ffAudio** [comment]
Ok, I improved the scaler code to be more general, thanks to the suggestions.
I could narrow the problem down to that the stream contains only I_FRAMEs...

**Comment by ffAudio** [comment]
ffprobe shows these errors:
ffprobe version N-83978-g0c6105d Copyright (c) 2007-2017 the FFmpeg developers
  built with Apple LLVM version 8.0.0 (clang-800.0.42.1)
  configuration: --cc=CC --arch=x86_64 --disable-static --enable-shared --prefix=/usr/local/Cellar/ffmpeg/3.1.3/
  libavutil      55. 48.100 / 55. 48.100
  libavcodec     57. 83.100 / 57. 83.100
  libavformat    57. 66.104 / 57. 66.104
  libavdevice    57.  3.100 / 57.  3.100
  libavfilter     6. 76.100 /  6. 76.100
  libswscale      4.  3.101 /  4.  3.101
  libswresample   2.  4.100 /  2.  4.100
[h264 @ 0x7fd37a808000] non-existing PPS 0 referenced
[h264 @ 0x7fd37a808000] decode_slice_header error
[h264 @ 0x7fd37a808000] no frame!
... repeating several times...
[h264 @ 0x7fd37a808000] non-existing PPS 0 referenced
[h264 @ 0x7fd37a808000] decode_slice_header error
[h264 @ 0x7fd37a808000] no frame!
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fd37a003400] decoding for stream 0 failed
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fd37a003400] Could not find codec parameters for stream 0 (Video: h264 (avc1 / 0x31637661), none, 800x600, 410 kb/s): unspecified pixel format
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'xxx.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.66.104
  Duration: 00:00:09.48, start: 0.000000, bitrate: 413 kb/s
    Stream #0:0(und): Video: h264 (avc1 / 0x31637661), none, 800x600, 410 kb/s, SAR 1:1 DAR 4:3, 25.11 fps, 25 tbr, 12800 tbn, 25600 tbc (default)
    Metadata:
      handler_name    : VideoHandler

**Comment by ffAudio** [comment]
Ok, writing a JUCE animation works now. I don't know, what the actual problem was, but cleaning up the code fixed it. Now it's also a bit more robust and better readable.

**Comment by matkatmusic** [comment]
Just wanted to ask if this line was the culprit for causing the all-black videos: 

https://github.com/filmstro/filmstro_ffmpeg/blob/master/modules/filmstro_ffmpeg/filmstro_ffmpeg_FFmpegVideoScaler.h#L123 

before you were setting it to `{data.data, data.data, data.data, data.data}`

**Comment by ffAudio** [comment]
That's fair to ask, sorry that I ruled that out so strictly, because you can find both versions in the examples. But you convinced me, that it might be more consistent to set the other colorplanes to nullptr.
The linesizes were definitely wrong, I found now a way to actually look them up in AVPixFmtDescriptor. Next was that some formats work, some not. E.g. mp4 still doesn't produce usable videos, but the same codec in mpeg does. 
So there is a lot to experiment and to learn about video formats, before it works for all cases. I mean afaik VLC uses ffmpeg as well, and it is a very long source code... They are the level to aim for, but it will probably never reach.
Thanks for trying and thinking with me, I hope it will be usefull for you!

**Comment by matkatmusic** [comment]
no problem, glad I could at least spawn ideas to try for solving.
